import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google"
import "./globals.css";
import { ClerkProvider} from '@clerk/nextjs'
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] })
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gymkhana IIITV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased ${inter.className}`}
      >
        {children}
      </body>
      <Toaster 
      position ="bottem-right"
      toastOptions={
      {
        style : {
          backgroundColor: '#0070f3',
          color: '#ffffff',
        }
      }
      }/>
    </html>
    </ClerkProvider>
  );
}
